// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALFU7YDZ1vnn4FhvyOe6xetyatYh8FZ0U',
    appId: '1:112440612335:web:80dc292f500dc8f65f121a',
    messagingSenderId: '112440612335',
    projectId: 'gestioninventariofpdam',
    authDomain: 'gestioninventariofpdam.firebaseapp.com',
    storageBucket: 'gestioninventariofpdam.firebasestorage.app',
    measurementId: 'G-N90GG1MECN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUIGjJEdmAS_P3TTV0ZGTSUkwdEDbnPzI',
    appId: '1:112440612335:android:4edd877ce75b41be5f121a',
    messagingSenderId: '112440612335',
    projectId: 'gestioninventariofpdam',
    storageBucket: 'gestioninventariofpdam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQmJPgRyHQPq_LoWEKR7DmX37vRhahO70',
    appId: '1:112440612335:ios:e5f2b33f0ce89d205f121a',
    messagingSenderId: '112440612335',
    projectId: 'gestioninventariofpdam',
    storageBucket: 'gestioninventariofpdam.firebasestorage.app',
    iosBundleId: 'com.example.gestioninventario1',
  );
}
